version: 2.1

jobs:
  one:
  #build:
    #working_directory: ~/repo
    docker:
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: traian07 
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
          POSTGRES_DB: $POSTGRES_DB
  two:
    docker:
      - image: cimg/node:16.1.0
        auth:
          username: traian07 
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          milanesa: true
    steps:
      - checkout
      # - run: npm install
      # Wait for Postgres connection to open.
      # - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Run validation checks & generate coverage reports
      # - run: npm run test 
      # Send coverage report to Codecov
      # - run: yarn start reportCoverage
      # - store_artifacts:
      #     path: ./coverage/clover.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: ./coverage/clover.xml