version: 2.1

jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER: $POSTGRES_USER
          - POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
          - POSTGRES_DB: $POSTGRES_DB
      - image: cimg/node:current
    steps:
      - checkout
      - run: node --version
    # steps:
    #   - run:
    #     command: npm i
    #   - run:
    #     command: npm run test