version: 2.1
orbs:
  node: circleci/node@3.0.0

workflows:
  node-tests:
    build: 
      docker:
        - image: circleci/postgres:9.6.2-alpine
          environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
            POSTGRES_DB: $POSTGRES_DB
    jobs:
      - node/test